
- name: gitlab container
  docker_container:
    name: gitlab
    image: gitlab/gitlab-ce
    published_ports:
      - 80:80
      - 22:22
    volumes:
      - /var/containers/gitlab/config:/etc/gitlab
      - /var/containers/gitlab/logs:/var/log/gitlab
      - /var/containers/gitlab/data:/var/opt/gitlab

- name: ensure gitlab configuration is set
  template:
    src: templates/gitlab.rb.j2
    dest: /var/containers/gitlab/config/gitlab.rb
  notify:
    - "reload gitlab"


