
- name: open up http/https ports
  with_items:
    - 80
    - 443
  ufw:
    rule: allow
    port: "{{item}}"
  notify:
    - "reload firewall"

- name: load balancer container
  docker_container:
    name: load_balancer
    image: nginx
    volumes:
      - /var/containers/_shared/letsencrypt:/etc/letsencrypt
      - /var/containers/load_balancer/conf.d:/etc/nginx/conf.d
    network_mode: host
    restart_policy: unless-stopped

- name: generate nginx configuration
  with_items:
    - fingerboard
    - chat
    - jenkins
    - jokes
  template:
    src: "templates/{{item}}.nginx.conf.j2"
    dest: "/var/containers/load_balancer/conf.d/{{item}}.nginx.conf"
  notify:
    - "reload nginx"
