- name: open up port for logstash
  with_items:
    - 5000
    - 5001
  ufw:
    to_ip: "{{ufw_default_to_ip}}"
    rule: allow
    port: "{{item}}"

- name: logstash directory
  file:
    state: directory
    path: /var/containers/logstash/pipeline

- name: generate pipeline config
  template:
    src: logstash.conf.j2
    dest: /var/containers/logstash/pipeline/logstash.conf
  notify:
    - "reload logstash"

- name: create logstash container
  docker_container:
    restart_policy: unless-stopped
    # Guess I can't make logstash log itself eh...
    log_driver: json-file
    name: logstash
    image: docker.elastic.co/logstash/logstash-oss:6.8.4
    network_mode: host
    volumes:
      - /var/containers/logstash/pipeline:/usr/share/logstash/pipeline
