groups:
  - name: down
    rules:
      - alert: Down
        expr: probe_success == 0
        for: 5m
        annotations:
          summary: "{{$labels.instance}} is down"
          description: "{{$labels.instance}} has been down for 5 minutes."
