version: '2'
services:
  front:
    image: nginx
    depends_on:
      - chat
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
  chat:
    image: aghost7/ninja-chat
    ports:
      - 9000:9000
    depends_on:
      - mongo
    volumes:
      - /root/.ivy2:/var/cache/ivy2
  certbot:
    image: aghost7/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  mongo:
    image: mongo
