version: '2'
services:
  chat:
    image: aghost7/ninja-chat
    ports:
      - 127.0.0.1:9000:9000
    depends_on:
      - mongo
    volumes:
      - /root/.ivy2:/var/cache/ivy2
  certbot:
    ports:
      - 6000:6000
    image: aghost7/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  mongo:
    image: mongo
