version: '2'
services:
  front:
    image: aghost7/portfolio-front
    depends_on:
      - chat
  chat:
    image: aghost7/ninja-chat
    ports:
      - 9000:9000
    depends_on:
      - mongo
    volumes:
      - /root/.ivy2:/var/cache/ivy2
  mongo:
    image: mongo
