version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce
    ports:
      - 80:80
      - 22:22
    volumes:
      - /var/containers/gitlab/config:/etc/gitlab
      - /var/containers/gitlab/logs:/var/log/gitlab
      - /var/containers/gitlab/data:/var/opt/gitlab
