version: '2'
services:
  chat:
    image: ./images/chat
    ports:
      - 127.0.0.1:9000:9000
    depends_on:
      - mongo
    volumes:
      - /root/.ivy2:/var/cache/ivy2
  certbot:
    ports:
      - 6000:6000
    image: ./images/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/certbot/secrets:/etc/certbot/secrets
  mongo:
    image: mongo
