version: '2'
services:
  chat:
    build:
      context: .
      dockerfile: chat.docker
    ports:
      - 9000:9000
    depends_on:
      - mongo
    volumes:
      - /root/.ivy2:/var/cache/ivy2
  mongo:
    image: mongo
