version: '2'
services:
  front:
    image: nginx
    depends_on:
      - chat
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
  chat:
    build: ./images/chat
    depends_on:
      - mongo
    volumes:
      - /root/.ivy2:/var/cache/ivy2
  certbot:
    build: ./images/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  mongo:
    image: mongo
