- hosts: k3s
  roles:
  - swap
  - k3s/common

- hosts: k3s_master
  roles:
  - k3s/master

- hosts: k3s_node
  roles:
  - k3s/node

- hosts: k3s_master
  roles:
  - certmanager
  - nginx_ingress

- hosts: k3s_master
  tasks:
    - name: create echo deployment
      k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: echo-server
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: echo-server
            template:
              metadata:
                labels:
                  app: echo-server
              spec:
                containers:
                - name: echo-server
                  image: "mendhak/http-https-echo"
                  ports:
                  - containerPort: 80

    - name: create echo service
      k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: echo-server-svc
            namespace: default
          spec:
            selector:
              app: echo-server
            ports:
            - port: 80
              targetPort: 80
              protocol: TCP
              name: http

    - name: create ingress
      k8s:
        definition:
          apiVersion: networking.k8s.io/v1beta1
          kind: Ingress
          metadata:
            name: echo-ingress
            namespace: default
            annotations:
              kubernetes.io/ingress.class: "nginx"
              cert-manager.io/cluster-issuer: jonathan-boudreau
          spec:
            tls:
            - hosts:
              - k3s.jonathan-boudreau.com
              - jonathan-boudreau.com
              secretName: ingress-tls-cert
            rules:
            - host: k3s.jonathan-boudreau.com
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    serviceName: echo-server-svc
                    servicePort: 80
