- name: set ca directory
  set_fact:
    vpn_controller_dir: "{{lookup('ENV', 'PWD')}}/{{vpn_controller_relative_dir}}"
    vpn_ca_dir: "{{ansible_env.HOME}}/ca"
    vpn_keys_dir: "{{ansible_env.HOME}}/ca/keys"

- name: checking if key exist
  register: client_key_stat
  stat:
    path: "{{vpn_keys_dir}}/{{vpn_client_name}}.key"

- name: generate client key
  when: not client_key_stat.stat.exists
  shell: |
    . vars
    ./build-key --batch {{vpn_client_name}}
  args:
    chdir: "{{vpn_ca_dir}}"

- name: load client ca
  register: vpn_client_ca
  command: cat "{{vpn_keys_dir}}/ca.crt"

- name: load client cert
  register: vpn_client_cert
  command: cat "{{vpn_keys_dir}}/{{vpn_client_name}}.crt"

- name: load client key
  register: vpn_client_key
  command: cat "{{vpn_keys_dir}}/{{vpn_client_name}}.key"

- name: load client tls_auth
  register: vpn_client_tls_auth
  command: cat "{{vpn_keys_dir}}/ta.key"

- name: ensure controller dir exists
  delegate_to: localhost
  file:
    state: directory
    path: "{{vpn_controller_dir}}"

- name: generate openvpn configuration
  delegate_to: localhost
  template:
    src:  client.ovpn.j2
    dest: "{{vpn_controller_dir}}/{{vpn_client_name}}.ovpn"
