
- name: set private ip
  set_fact:
    private_ip: "{{ ansible_eth1['ipv4']['address'] }}"

- name: create systemd unit file
  template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
  register: k3s_service

- name: enable k3s server
  when: k3s_service.changed
  systemd:
    name: k3s
    daemon_reload: True
    state: restarted
    enabled: True

- name: grab authentication token
  slurp:
    path: /var/lib/rancher/k3s/server/token
  register: k3s_token_file

- name: set token
  set_fact:
    k3s_token: "{{ k3s_token_file.content | b64decode | trim }}"

- name: install pip
  apt:
    name: python3-pip

- name: install python dependencies
  pip:
    name:
      - kubernetes
      - openshift

- name: check if helm is installed
  stat:
    path: /usr/local/bin/helm
  register: helm

- name: add kubectl link
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: create config
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: add kube config link
  file:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_env.HOME }}/.kube/config"
    state: link

- name: add shorthands to bashrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      n=default
      alias k='kubectl --namespace=$n'

- name: install helm
  when: not helm.stat.exists
  include_tasks: ./helm.yml
