
- name: open db port firewall only for front server
  with_items: "{{groups['front']}}"
  ufw:
    rule: allow
    from_ip: "{{item}}"
    port: 27017
  notify:
    - reload firewall

- name: create mongo container
  docker_container:
    image: mongo
    name: mongo
    network_mode: host
    restart_policy: unless-stopped
    volumes:
      - /var/containers/chat_mongo/db:/data/db
      - /var/containers/chat_mongo/config_db:/data/config_db
