global:
  scrape_interval: 30s
  evaluation_interval: 30s
scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [prometheus]
    honor_labels: true
    # For now, use dns for service discovery. Will move over to kubernetes
    # when I'm done with metrics stuff. This isn't optimal.
    dns_sd_configs:
    - names:
      - '_metrics._tcp.jonathan-boudreau.com'
