- name: download manifests
  get_url:
    force: True
    url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.34.1/deploy/static/provider/baremetal/deploy.yaml"
    dest: /tmp/nginx-ingress.yml

- name: install nginx-ingress
  k8s:
    src: /tmp/nginx-ingress.yml

- name: create entrypoint into cluster
  k8s:
    apply: True
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: ingress-nginx-controller
        namespace: ingress-nginx
      spec:
        type: NodePort
        ports:
          - name: http
            port: 80
            protocol: TCP
            nodePort: 30080
          - name: https
            port: 443
            protocol: TCP
            nodePort: 30443
        selector:
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/instance: ingress-nginx
          app.kubernetes.io/component: controller
        externalIPs:
        - "{{ ansible_eth0.ipv4.address }}"
