
#- name: create certmanager namespace
#  community.kubernetes.k8s:
#    apply: True
#    definition:
#      apiVersion: v1
#      kind: Namespace
#      metadata:
#        name: cert-manager

- name: add jetstack repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: install certmanager
  kubernetes.core.helm:
    name: cert-manager
    create_namespace: True
    release_namespace: cert-manager
    chart_version: 1.8.0
    chart_ref: jetstack/cert-manager
    values:
      webhook.enabled: false
      installCRDs: true

- name: create secret
  community.kubernetes.k8s:
    definition:
      kind: Secret
      metadata:
        name: digitalocean-dns
        namespace: cert-manager
      type: Opaque
      data:
        access-token: "{{ certmanager_digitalocean_key | b64encode }}"

- name: create cert issuer
  community.kubernetes.k8s:
    apply: True
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: jonathan-boudreau
        namespace: cert-manager
      spec:
        acme:
          email: jonathan.boudreau.92@gmail.com
          server: "https://acme-v02.api.letsencrypt.org/directory"
          privateKeySecretRef:
            name: jonathan-boudreau-key
          solvers:
          - dns01:
              digitalocean:
                tokenSecretRef:
                  name: digitalocean-dns
                  key: access-token
