
- name: build image certbot
  delegate_to: localhost
  docker_image:
    force: True
    push: True
    name: aghost7/certbot-dns-digitalocean
    path: images/certbot

- name: open up certbot port
  ufw:
    rule: allow
    port: 6000

- name: create container
  docker_container:
    pull: True
    name: certbot
    image: aghost7/certbot-dns-digitalocean
    network_mode: host
    restart_policy: unless-stopped
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - /var/containers/certbot/secrets:/etc/certbot/secrets
      - /var/containers/_shared/letsencrypt:/etc/letsencrypt
