- name: build git image
  delegate_to: localhost
  docker_image:
    force: True
    push: True
    name: aghost7/git-server
    path: images/git

- name: ensure keys directory exists
  file:
    state: directory
    path: /var/containers/git/keys/authorized_keys

- name: add public key to authorized_keys
  with_items:
    - "{{ci_local_ssh_public_key}}"
    - "{{ci_jenkins_ssh_public_key}}"
  lineinfile:
    path: /var/containers/git/keys/authorized_keys/git
    line: "{{lookup('file', item)}}"

- name: git docker container
  docker_container:
    image: aghost7/git-server
    name: git
    volumes:
      - /var/containers/git/repos:/repos
      - /var/containers/git/keys:/keys
    ports:
      - 0.0.0.0:22:22

- name: ensure repos are initialized
  with_items: "{{git_repos}}"
  register: git_init
  changed_when: git_repos.stdout_lines|length > 0
  args:
    chdir: /var/containers/git/repos
  shell: |
    if [ ! -d "{{item}}.git" ]; then
      git init --bare "{{item}}".git
    fi

- name: add post-receive hook
  vars:
    jenkins_build_url: "{{jenkins_base_url}}/buildWithParameters?token={{jenkins_fingerboard_build_token}}"
  template:
    src: templates/post-receive.j2
    dest: "/var/containers/git/repos/fingerboard.git/hooks/post-receive"
