- name: build jenkins image
  delegate_to: localhost
  docker_image:
    pull: True
    force: True
    push: True
    name: aghost7/jenkins-ansible
    path: images/jenkins

- name: create ansible user
  user:
    name: ansible
    uid: 1000
    groups:
      - docker
      - sudo

- name: create jenkins directory
  file:
    state: directory
    owner: 1000
    path: /var/containers/jenkins/jenkins_home

- name: open up jenkins port to load balancer
  with_items: "{{groups['front']}}"
  ufw:
    rule: allow
    from_ip: "{{item}}"
    port: 8080

- name: find docker gid
  register: docker_gid
  shell: "cat /etc/group  | grep -E '^docker' | cut -d : -f 3"

- name: jenkins docker image
  docker_container:
    pull: True
    restart_policy: on-failure
    name: jenkins
    image: aghost7/jenkins-ansible
    groups:
      - "{{docker_gid.stdout}}"
    volumes:
      - /var/containers/jenkins/jenkins_home:/var/jenkins_home
      - /run/docker.sock:/run/docker.sock
    network_mode: host
