- name: build prometheus image
  delegate_to: localhost
  docker_image:
    force: True
    push: True
    name: aghost7/prometheus-dns-netdata
    path: images/prometheus

- name: create prometheus container
  docker_container:
    name: prometheus
    # Use json-file since we need prometheus to monitor the elasic logger. They
    # shouldn't be interdependent in case elastic fails.
    log_driver: json-file
    image: aghost7/prometheus-dns-netdata
    ports:
      # requires an ssh tunnel to access
      - 127.0.0.1:9090:9090
    restart_policy: unless-stopped
    volumes:
      - /var/containers/prometheus/prometheus:/prometheus

# TODO: Will need to leverage prometheus to check application status:
# https://github.com/prometheus/blackbox_exporter
# Alerts can be done from prometheus...
