- name: create config directory
  loop:
    - prometheus
    - blackbox_exporter
  file:
    state: directory
    path: /var/containers/{{item}}/config

- name: ensure the config file exists
  file:
    state: touch
    path: /var/containers/prometheus/config/prometheus.yml

- name: open up firewall
  ufw:
    rule: allow
    direction: in
    interface: lo
    port: 9090
  notify:
    - "reload firewall"

- name: create prometheus container
  docker_container:
    name: prometheus
    pull: True
    # Use json-file since we need prometheus to monitor the elasic logger. They
    # shouldn't be interdependent in case elastic fails.
    log_driver: json-file
    image: prom/prometheus
    command: "--config.file=/etc/prometheus/config/prometheus.yml"
    network_mode: host
    restart_policy: unless-stopped
    volumes:
      - /var/containers/prometheus/prometheus:/prometheus
      - /var/containers/prometheus/config:/etc/prometheus/config

- name: generate prometheus config
  template:
    src: prometheus.yml.j2
    dest: /var/containers/prometheus/config/prometheus.yml
  notify:
    - "reload prometheus"

- name: bring up the blackbox exporter
  docker_container:
    name: blackbox_exporter
    log_driver: json-file
    image: prom/blackbox-exporter:v0.14.0
    network_mode: host
    restart_policy: always
    volumes:
      - /var/containers/blackbox_exporter/config:/config
    command: "--config.file=/config/blackbox.yml"

- name: generate blackbox config
  template:
    src: blackbox.yml.j2
    dest: /var/containers/blackbox_exporter/config/blackbox.yml
  notify:
    - "reload blackbox_exporter"
# TODO: Will need to leverage prometheus to check application status:
# https://github.com/prometheus/blackbox_exporter
# Alerts can be done from prometheus...
