- name: create config directory
  file:
    state: directory
    path: /var/containers/prometheus/config

- name: ensure the config file exists
  file:
    state: touch
    path: /var/containers/prometheus/config/prometheus.yml

- name: create prometheus container
  docker_container:
    name: prometheus
    pull: True
    # Use json-file since we need prometheus to monitor the elasic logger. They
    # shouldn't be interdependent in case elastic fails.
    log_driver: json-file
    image: prom/prometheus
    command: "--config.file=/etc/prometheus/config/prometheus.yml"
    ports:
      # requires an ssh tunnel to access
      - 127.0.0.1:9090:9090
    restart_policy: unless-stopped
    volumes:
      - /var/containers/prometheus/prometheus:/prometheus
      - /var/containers/prometheus/config:/etc/prometheus/config

- name: generate prometheus config
  template:
    src: prometheus.yml.j2
    dest: /var/containers/prometheus/config/prometheus.yml
  notify:
    - "reload prometheus"

# TODO: Will need to leverage prometheus to check application status:
# https://github.com/prometheus/blackbox_exporter
# Alerts can be done from prometheus...
