- name: open up elasticsearch port
  with_items: "{{groups['data']}}"
  ufw:
    rule: allow
    to_ip: "{{ufw_default_to_ip}}"
    from_ip: "{{item}}"
    port: 9200

- name: increase mapping size for elasticsearch
  sysctl:
    name: vm.max_map_count
    value: 262144

- name: create elasticsearch data directory
  file:
    state: directory
    path: /var/containers/elasticsearch/data
    # required uid for elasticsearch to work correctly
    group: 1000
    owner: 1000

- name: create elasticsearch container
  docker_container:
    restart_policy: unless-stopped
    log_driver: json-file
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.4
    network_mode: host
    volumes:
      - /var/containers/elasticsearch/data:/usr/share/elasticsearch/data
    env:
      indices.fielddata.cache.size: 5%
      http.cors.allow-origin: '/.*/'
      http.cors.enabled: 'true'
      http.cors.allow-headers: 'X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization'
      http.cors.allow-credentials: 'true'
