- name: add mongodb ip to hosts file
  with_items: "{{groups['data']}}"
  lineinfile:
    path: /etc/hosts
    line: "{{item}} mongo"

- name: create app container
  docker_container:
    network_mode: host
    restart_policy: unless-stopped
    name: chat_app
    image: aghost7/ninja-chat
    env:
      JAVA_OPTS: '-XX:+UseCompressedOops -Xms50m -Xmx50m'
