- name: set master hostvars
  set_fact:
    k3s_master_hostvars: "{{ hostvars[groups['k3s_master'][0]] }}"

- name: set template facts
  set_fact:
    k3s_master_token: "{{ k3s_master_hostvars['k3s_token'] }}"
    k3s_master_address: "{{ k3s_master_hostvars['ansible_eth1']['ipv4']['address'] }}"

- name: create systemd unit file
  template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
  register: k3s_service

- name: enable k3s node
  when: k3s_service.changed
  systemd:
    name: k3s
    daemon_reload: True
    state: restarted
    enabled: True

- name: set label
  retries: 5
  delay: 15
  delegate_to: "{{ groups['k3s_master'][0] }}"
  command: kubectl label node --overwrite {{ ansible_hostname }} kubernetes.io/role=worker
